### ISSUE TITLE
`transform-genbank-location` should be noiser about violated expectations

### ISSUE THREAD

**Issue by genehack** [nextstrain/ingest#35]
### Current Behavior
Currently, `transform-genbank-location` [depends on the value of the `database` field](https://github.com/nextstrain/ingest/blob/main/transform-genbank-location#L38-L40), and silently no-ops if this field is missing or not one of the expected values.

### Expected behavior
The script should emit a warning when the input lacks the expected value in the `database` field or if the field is missing, to make it more clear that it's not actually changing data. 

### How to reproduce
Steps to reproduce the current behavior:
1. Run the script on a NDJSON record that doesn't have a `database` field
2. Observe that the script runs, exits without error

### Possible solution
Emitting a warning to STDERR on the `else` branch of the core conditional in the main section.

**Comment by joverlee521** [comment]
100% support louder warnings when curation scripts don't change data as expected. 

This is the pattern used in the formal `augur curate` commands (e.g. [augur curate titlecase](https://github.com/nextstrain/augur/blob/c241569a8846ddfd26a295e8f48d1231e39b0685/augur/curate/titlecase.py#L101-L108)), but not as enforced in this repo because it was supposed to be a temporary home for these scripts.
